version: "3.9"

services:
  vault:
    container_name: vault
    image: vault:1.13.0
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak:21.0.2-debian-11-r2
    ports:
      - "10000:8080"
    environment:
      - "KEYCLOAK_ADMIN_USER=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_MANAGEMENT_USER=admin"
      - "KEYCLOAK_MANAGEMENT_PASSWORD=admin"
      - "KEYCLOAK_DATABASE_VENDOR=dev-file"